name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/wisecow-app .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        kubectl-version: 'latest'

    # Set up kubeconfig from GitHub Secrets
    - name: Set kubeconfig
      run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    # Verify kubectl is working
    - name: Verify kubectl
      run: kubectl version --client

    # - name: Start Minikube
    #   run: minikube start --driver=docker

    # - name: Set kubectl context
    #   run: kubectl config use-context minikube

    - name: Apply Kubernetes Deployment
      run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
      working-directory: ./  # Ensure you're running this from the root or correct directory

    # - name: Wait for Pod to be Ready
    #   run: |
    #     # Loop until the pod is ready
    #     while true; do
    #       # Check if the pod is ready
    #       kubectl get pods -l app=wisecow -o=jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' | grep -q "True" && break
    #       echo "Waiting for pod to be ready..."
    #       sleep 10  # Wait for 10 seconds before checking again
    #     done
    #     echo "Pod is ready!"
      
    # - name: Port-forward the service
    #   run: |
    #     kubectl port-forward service/wisecow 4499:4499 &
    #     sleep 10  # Give it some time for the port-forward to establish
    #     curl http://localhost:4499
