name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/wisecow-app .

    - name: Push Docker image
      run: docker push ${{ secrets.REGISTRY_USERNAME }}/wisecow-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to k8s
      uses: kubernetes-actions/setup-kubectl@v1
      with:
        version: 'latest'
        args: apply -f kubernetes/
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
