name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/wisecow-app .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/wisecow-app:latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubectl-version: 'latest'

      # Set up kubeconfig from GitHub Secrets
      - name: Set kubeconfig
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

     # Verify kubectl is working
      - name: Verify kubectl
        run: kubectl version --client

    # - name: Start Minikube
    #   run: minikube start --driver=docker

    # - name: Set kubectl context
    #   run: kubectl config use-context minikube

      - name: Apply Kubernetes Deployment
        run: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
        working-directory: ./  # Ensure you're running this from the root or correct directory

      - name: List all services for debugging
        run: kubectl get svc  
        
      # - name: Get the URL of the deployed application
      #   run: |
      #     # Get the service name based on the label selector (e.g., app=wisecow)
      #     SERVICE_NAME=$(kubectl get svc -l app=wisecow -o jsonpath='{.items[0].metadata.name}')
      #     echo "Service name found: $SERVICE_NAME"

      #     # Get the URL of the deployed service
      #     SERVICE_URL=$(kubectl get svc $SERVICE_NAME -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
      #     echo "Service is available at: http://${SERVICE_URL}"

    # - name: Wait for Pod to be Ready
    #   run: |
    #     # Loop until the pod is ready
    #     while true; do
    #       # Check if the pod is ready
    #       kubectl get pods -l app=wisecow -o=jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' | grep -q "True" && break
    #       echo "Waiting for pod to be ready..."
    #       sleep 10  # Wait for 10 seconds before checking again
    #     done
    #     echo "Pod is ready!"
      
    # - name: Port-forward the service
    #   run: |
    #     kubectl port-forward service/wisecow 4499:4499 &
    #     sleep 10  # Give it some time for the port-forward to establish
    #     curl http://localhost:4499
